### ISSUE TITLE
[Bug]: Adetailer error during img2img upscale (RecursionError: maximum recursion depth exceeded)

### ISSUE THREAD

**Issue by Vinzero-SS** [Panchovix/stable-diffusion-webui-forge#2]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ✔ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [✔  ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When using [Adetailer](https://github.com/Bing-su/adetailer) during the img2img process, the webui throws an error and aborts the process.

This issue didn't happen with the dev2 version of Forge, so I'm assuming something must have change\broke with this updated version.

Oddly enough, Adetailer works just fine during txt2img while generating normal resolution images, the problem only occurs within img2img.

### Steps to reproduce the problem

1) Download & install the official [Adetailer](https://github.com/Bing-su/adetailer) extension.
2) Generate an image and send to img2img
3) Enable Adetailer and select any Adetailer detector, other image settings shouldn't matter.
4) Wait for the img2img upscale to finish and for the usual Adetailer process to begin, it will error out in the console with "RecursionError: maximum recursion depth exceeded"

### What should have happened?

With the Dev2 and Main branch, Adetailer was working normally.

### What browsers do you use to access the UI ?

Firefox

### Sysinfo

[sysinfo-2024-07-08-00-19.json](https://github.com/user-attachments/files/16121473/sysinfo-2024-07-08-00-19.json)

### Console logs

```Shell
https://pastebin.com/BgwMLgMB
```

**Comment by Panchovix** [comment]
Can confirm the issue, gonna check why.

**Comment by Panchovix** [comment]
I have pushed a new commit https://github.com/Panchovix/stable-diffusion-webui-forge/commit/101af34f83819de8591bdc3c7e11c6fb9466fb03

In theory can be 0.1-0.2 slower than before, but it should fix this and also soft inpainting.

Can you check if it works fine for you?

**Comment by Vinzero-SS** [comment]
@Panchovix 

I can confirm it works! I just tested img2img in two ways:

1) Same resolution + Adetailer Enabled
2) Latent upscale script + 1.5x res + Adetailer Enabled

Both worked as expected with zero issues.
Thank you for fixing the issue so quickly!

**Comment by Vinzero-SS** [comment]
The following issue isn't related to the above, since it seems relatively minor. I can open a new thread if you want though.

When clicking on the folder icon for "Open Images output directory" on either txt2img or img2img, the console log returns and error and no folder opens:

https://pastebin.com/5heX91aG

This is something I just noticed after trying to open the output folder.
Let me know if you would like a different thread for this.

**Comment by Panchovix** [comment]
> The following issue isn't related to the above, since it seems relatively minor. I can open a new thread if you want though.
> 
> When clicking on the folder icon for "Open Images output directory" on either txt2img or img2img, the console log returns an error and no folder opens:
> 
> https://pastebin.com/5heX91aG
> 
> This is something I just noticed after trying to open the output folder. Let me know if you would like a different thread for this.

Just pushed another commit (https://github.com/Panchovix/stable-diffusion-webui-forge/commit/b54df7487f7febfff20a51ce36154f3b3e7b8461) that fixes it. I was missing 2 functions from utils.py. Please try it and tell me how it goes.

**Comment by Vinzero-SS** [comment]
@Panchovix 

Yup, fixed! Both txt2img and img2img output folders open normally.

You can close and mark this thread as solved, I'll open any new issues with a new thread.
Thank you for the quick fixes!
