### ISSUE TITLE
[Feature Request]: Update "Github" link in footer for your branch

### ISSUE THREAD

**Issue by altoiddealer** [Panchovix/stable-diffusion-webui-forge#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

![Screenshot 2024-07-11 095749](https://github.com/Panchovix/stable-diffusion-webui-forge/assets/1613484/5594f2da-f519-496d-925e-473ab172da2a)

Just suggesting to have this link to your branch

### Proposed workflow

1. Run the WebUI
2. Click the GitHub link on the bottom
3. Takes you to [Panchovix dev_upstream_a1111](https://github.com/Panchovix)
[stable-diffusion-webui-forge](https://github.com/Panchovix/stable-diffusion-webui-forge) instead of main branch

**Comment by Panchovix** [comment]
Noted, did it on https://github.com/Panchovix/stable-diffusion-webui-forge/commit/96a2dc4d2523ccc52ae55b52176d83e48f41b4c4

Thanks for the suggestion!
